
PROGS := matterStates rangeSum maxMin numGuess fileAdder smallSort fallDistance isPalindrome

all: $(PROGS)

matterState: matterState.cpp
	g++ -g matterState.cpp -o matterState

rangeSum: rangeSum.cpp
	g++ -g rangeSum.cpp -o rangeSum

maxMin: maxMin.cpp
	g++ -g maxMin.cpp -o maxMin

numGuess: numGuess.cpp
	g++ -g numGuess.cpp -o numGuess

fileAdder: fileAdder.cpp
	g++ -g fileAdder.cpp -o fileAdder

smallSort: smallSort.cpp
	g++ -g smallSort.cpp -o smallSort

fallDistance: fallDistance.cpp
	g++ -g fallDistance.cpp -o fallDistance

isPalindrome: isPalindrome.cpp
	g++ -g isPalindrome.cpp -o isPalindrome

hailstone: hailstone.cpp
	g++ -g hailstone.cpp -o hailstone


clean:
	rm -f $(PROGS) *.o *~